[package]
edition = "2021"
name = "armqr"
version = "0.2.0"

[dependencies]
askama = "0.12.0"
base64 = "0.21.2"
rocket = "0.5.0-rc.3"
serde = "1.0.183"
serde_json = "1.0.105"
uuid = { version = "1.4.1", features = ["serde", "v4"] }
