name: "Build"
on:
  pull_request: {}
  push: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        install_url: https://nixos-nix-install-tests.cachix.org/serve/vij683ly7sl95nnhb67bdjjfabclr85m/install
        install_options: '--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve'
        extra_nix_config: |
          experimental-features = nix-command flakes
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    - uses: cachix/cachix-action@v10
      with:
        name: astralbijection
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - run: nix build --no-link .#armqr

    - run: >
        docker load -i $(nix build --json --no-link .#dockerImages.x86_64-linux.armqr
        | jq -r '.[0].outputs.out'
        | sed -r 's/Loaded image: (.*)$/\\1/'
        | tee /tmp/imagetag

    - run: >
        docker tag $(</tmp/imagetag) armqr:latest
      if: github.ref == 'refs/heads/main'

    - run: >
        docker push $(</tmp/imagetag)

    - run: docker push armqr:latest
      if: github.ref == 'refs/heads/main'
    
