name: "Build"
on:
  pull_request: {}
  push: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4

    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - uses: cachix/cachix-action@v12
      with:
        name: astralbijection
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: Build armqr binary
      run: nix build --no-link .#armqr
